POST http://localhost:4000/app/Signed
content-type: application/json 

{
    "Surname": "Olabiyi",
    "OtherName": "Oluwaferanmi",
    "Email": "Pheranmyolabiyigmail.com",
    "Username": "Pheranmy",
    "Password": "12345",
    "ConfirmPssword": "12345",
}

//dont leave a space after line 1
//wrap your contents in quotes since it is a json file